### ISSUE TITLE
STOMP smoothing adapter as post presuccesor of OMPL does not work

### ISSUE THREAD

**Issue by jaytjoa** [ros-industrial/stomp_ros#15]
Hi! I have implemented the planning adapter by using OMPL before STOMP but somehow there is an error in console  

> Exception while loading planning adapter plugin 'stomp/SmoothingAdapter': According to the loaded plugin descriptions the class stomp/SmoothingAdapter with base class type planning_request_adapter::PlanningRequestAdapter does not exist.

I have followed the step in the moveit tutorial and my distro is kinetic in linux 16.04.

Any solution for this issue?

**Comment by marip8** [comment]
@jaytjoa this is currently being addressed in #7. It looks like there is a (potentially working) branch with the changes requested in the pull request [here](https://github.com/henningkayser/stomp_ros/pull/1)

**Comment by jrgnicho** [comment]
fixed in #20

**Comment by iskandersauma** [comment]
There is a problem with the adapter still. from what I understand fillTrajectory that is described in the moveit page does not exist hence we are forced to use other initialization methods such as linear interpolation.
